channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - python[version='3.8']
  - pandas>=1
  - numpy=1.19
  - tensorflow-gpu=2.2.0 #=2.4.1
  - scikit-learn=0.24.1
  - nbconvert=6.0.7
  - gast=0.3.3
  - ipykernel=5.3.4
  - pydot=1.4.1
  - graphviz=2.40.1
  - pip
  - pip:
      - -e .
