channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.3.4
  - python[version='3.8']
  - pandas=1.2.4
  - numpy=1.19.2
  - tensorflow-gpu=2.4.1
  - scikit-learn=0.24.2
  - nbconvert=6.1.0
  - ipykernel=5.3.4
  - pydot=1.4.1
  - graphviz=2.40.1
  - pip
  - pip:
      - gast==0.3.3 # see https://github.com/tensorflow/tensorflow/issues/48889
      - -e .
